Support serializing named structs via YAML.
YAML de-serialization seems to call #respond_to? before instance
variables have been set. This is a problem because we check @attributes
to determine which methods we respond to.

    NoMethodError: undefined method `has_key?' for nil:NilClass
    Shared Example Group: "a serializable" called from ./spec/named_mutable_spec.rb:17
    # ./lib/finer_struct/anonymous_mutable.rb:19:in `respond_to?'
    # ./spec/shared_examples/serializable.rb:7:in `block (2 levels) in <top (required)>'

The solution proposed here introduces a check to ensure we have a
non-nil @attributes before accessing the keys.